import React, { useEffect, useState } from "react";
import {
  generateInterview,
  submitInterview,
} from "../../api/interviewApi";

export default function Interview() {
  const [targetRole, setTargetRole] = useState("");

  const [interview, setInterview] = useState(null);

  const [answers, setAnswers] = useState([]);

  const [loading, setLoading] = useState(false);

  const [submitting, setSubmitting] = useState(false);

  const [submitted, setSubmitted] = useState(false);

  const [result, setResult] = useState(null);

  // ---------------------------------
  // Generate Interview
  // ---------------------------------

  const handleGenerate = async () => {
    if (!targetRole.trim()) {
      alert("Please enter your target role.");
      return;
    }

    try {
      setLoading(true);

      const res = await generateInterview(
        targetRole.trim()
      );

      console.log("Interview:", res.data);

      const newInterview = res.data.interview;

      setInterview(newInterview);

      setAnswers(
        newInterview.questions.map(() => "")
      );

      setSubmitted(false);

      setResult(null);

    } catch (error) {
      console.log(
        "Interview Generate Error:",
        error.response?.data
      );

      alert(
        error.response?.data?.message ||
        "Failed to generate interview."
      );
    } finally {
      setLoading(false);
    }
  };

  // ---------------------------------
  // Answer Change
  // ---------------------------------

  const handleAnswerChange = (index, value) => {
    const updatedAnswers = [...answers];

    updatedAnswers[index] = value;

    setAnswers(updatedAnswers);
  };

  // ---------------------------------
  // Submit Interview
  // ---------------------------------

  const handleSubmit = async () => {
    if (!interview) return;

    const emptyAnswers = answers.some(
      (answer) => !answer.trim()
    );

    if (emptyAnswers) {
      const confirmSubmit = window.confirm(
        "Some questions are unanswered. Do you want to submit?"
      );

      if (!confirmSubmit) return;
    }

    try {
      setSubmitting(true);

      const res = await submitInterview(
        interview._id,
        answers
      );

      console.log("Submit Response:", res.data);

      setResult(res.data.interview);

      setInterview(res.data.interview);

      setSubmitted(true);

      alert("Interview submitted successfully!");

    } catch (error) {
      console.log(
        "Submit Error:",
        error.response?.data
      );

      alert(
        error.response?.data?.message ||
        "Failed to submit interview."
      );
    } finally {
      setSubmitting(false);
    }
  };

  // ---------------------------------
  // Initial Screen
  // ---------------------------------

  if (!interview) {
    return (
      <div style={styles.container}>

        <div style={styles.heroCard}>

          <div style={styles.icon}>
            🎤
          </div>

          <h1 style={styles.heroTitle}>
            AI Mock Interview
          </h1>

          <p style={styles.heroText}>
            Practice realistic interviews with AI,
            improve your communication, technical
            knowledge and interview confidence.
          </p>

          <div style={styles.inputBox}>

            <input
              type="text"
              placeholder="Enter target role e.g. Full Stack Developer"
              value={targetRole}
              onChange={(e) =>
                setTargetRole(e.target.value)
              }
              style={styles.input}
            />

            <button
              onClick={handleGenerate}
              disabled={loading}
              style={{
                ...styles.generateButton,
                opacity: loading ? 0.7 : 1,
              }}
            >
              {loading
                ? "Generating..."
                : "🚀 Start AI Interview"}
            </button>

          </div>

        </div>

        <div style={styles.infoGrid}>

          <div style={styles.infoCard}>
            <div style={styles.infoIcon}>🧠</div>
            <h3>AI Questions</h3>
            <p>
              Get role-specific interview questions
              generated by AI.
            </p>
          </div>

          <div style={styles.infoCard}>
            <div style={styles.infoIcon}>💬</div>
            <h3>Practice Answers</h3>
            <p>
              Answer questions just like a real
              interview.
            </p>
          </div>

          <div style={styles.infoCard}>
            <div style={styles.infoIcon}>📊</div>
            <h3>AI Evaluation</h3>
            <p>
              Receive score and detailed feedback
              for every answer.
            </p>
          </div>

          <div style={styles.infoCard}>
            <div style={styles.infoIcon}>🎯</div>
            <h3>Improve Skills</h3>
            <p>
              Identify weaknesses and improve your
              interview performance.
            </p>
          </div>

        </div>

      </div>
    );
  }

  // ---------------------------------
  // Interview Screen
  // ---------------------------------

  return (
    <div style={styles.container}>

      {/* Header */}

      <div style={styles.topHeader}>

        <div>
          <span style={styles.badge}>
            🤖 AI POWERED
          </span>

          <h1 style={styles.title}>
            {interview.targetRole} Interview
          </h1>

          <p style={styles.subtitle}>
            Answer each question carefully.
            Your answers will be evaluated by AI.
          </p>
        </div>

        <div style={styles.questionCount}>
          <strong>
            {interview.questions.length}
          </strong>

          <span>
            Questions
          </span>
        </div>

      </div>

      {/* Questions */}

      <div>

        {interview.questions.map(
          (question, index) => (

            <div
              key={index}
              style={styles.questionCard}
            >

              <div style={styles.questionHeader}>

                <span style={styles.questionNumber}>
                  Question {index + 1}
                </span>

                <span style={styles.questionLabel}>
                  {index < 3
                    ? "Technical"
                    : "Interview"}
                </span>

              </div>

              <h2 style={styles.question}>
                {question.question}
              </h2>

              <textarea
                placeholder="Type your answer here..."
                value={answers[index] || ""}
                onChange={(e) =>
                  handleAnswerChange(
                    index,
                    e.target.value
                  )
                }
                disabled={submitted}
                style={styles.textarea}
              />

              {/* Feedback */}

              {submitted &&
                question.feedback && (

                  <div style={styles.feedbackBox}>

                    <h4>
                      🤖 AI Feedback
                    </h4>

                    <p>
                      {question.feedback}
                    </p>

                    <h4>
                      💡 Improvement
                    </h4>

                    <p>
                      {question.improvement}
                    </p>

                    <div style={styles.score}>
                      Score:{" "}
                      <strong>
                        {question.score}/100
                      </strong>
                    </div>

                  </div>

                )}

            </div>

          )
        )}

      </div>

      {/* Submit */}

      {!submitted ? (

        <div style={styles.submitArea}>

          <button
            onClick={handleSubmit}
            disabled={submitting}
            style={styles.submitButton}
          >
            {submitting
              ? "🤖 Evaluating Answers..."
              : "🚀 Submit Interview"}
          </button>

        </div>

      ) : (

        <div style={styles.resultCard}>

          <div style={styles.resultIcon}>
            🏆
          </div>

          <h2>
            Interview Completed!
          </h2>

          <p>
            Your AI interview score
          </p>

          <div style={styles.totalScore}>
            {result?.totalScore || 0}
            <span>/100</span>
          </div>

          <button
            onClick={() => {
              setInterview(null);
              setAnswers([]);
              setSubmitted(false);
              setResult(null);
            }}
            style={styles.newInterviewButton}
          >
            🔄 Start New Interview
          </button>

        </div>

      )}

    </div>
  );
}

const styles = {

  container: {
    padding: "30px",
    background: "#f5f7fb",
    minHeight: "100vh",
  },

  heroCard: {
    maxWidth: "850px",
    margin: "30px auto",
    padding: "55px",
    background: "#fff",
    borderRadius: "24px",
    textAlign: "center",
    boxShadow:
      "0 15px 45px rgba(0,0,0,0.08)",
  },

  icon: {
    fontSize: "65px",
    marginBottom: "10px",
  },

  heroTitle: {
    fontSize: "38px",
    margin: "10px 0",
    color: "#111827",
  },

  heroText: {
    maxWidth: "650px",
    margin: "0 auto 30px",
    color: "#6b7280",
    fontSize: "17px",
    lineHeight: "1.7",
  },

  inputBox: {
    display: "flex",
    gap: "12px",
    maxWidth: "650px",
    margin: "auto",
  },

  input: {
    flex: 1,
    padding: "15px",
    border: "1px solid #d1d5db",
    borderRadius: "10px",
    fontSize: "15px",
    outline: "none",
  },

  generateButton: {
    padding: "15px 25px",
    background: "#2563eb",
    color: "#fff",
    border: "none",
    borderRadius: "10px",
    fontWeight: "700",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },

  infoGrid: {
    maxWidth: "1100px",
    margin: "30px auto",
    display: "grid",
    gridTemplateColumns:
      "repeat(auto-fit,minmax(220px,1fr))",
    gap: "20px",
  },

  infoCard: {
    background: "#fff",
    padding: "25px",
    borderRadius: "16px",
    boxShadow:
      "0 5px 20px rgba(0,0,0,0.05)",
  },

  infoIcon: {
    fontSize: "32px",
    marginBottom: "10px",
  },

  topHeader: {
    background: "#fff",
    padding: "30px",
    borderRadius: "18px",
    marginBottom: "25px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    boxShadow:
      "0 5px 20px rgba(0,0,0,0.05)",
  },

  badge: {
    background: "#dbeafe",
    color: "#2563eb",
    padding: "6px 12px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "700",
  },

  title: {
    fontSize: "30px",
    margin: "15px 0 5px",
  },

  subtitle: {
    color: "#6b7280",
  },

  questionCount: {
    background: "#eff6ff",
    padding: "18px 25px",
    borderRadius: "15px",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
  },

  questionCard: {
    background: "#fff",
    padding: "30px",
    marginBottom: "20px",
    borderRadius: "18px",
    boxShadow:
      "0 5px 20px rgba(0,0,0,0.05)",
  },

  questionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "15px",
  },

  questionNumber: {
    color: "#2563eb",
    fontWeight: "700",
  },

  questionLabel: {
    background: "#f3f4f6",
    padding: "6px 12px",
    borderRadius: "20px",
    fontSize: "12px",
  },

  question: {
    fontSize: "20px",
    lineHeight: "1.5",
    marginBottom: "20px",
  },

  textarea: {
    width: "100%",
    minHeight: "150px",
    padding: "15px",
    border: "1px solid #d1d5db",
    borderRadius: "12px",
    fontSize: "15px",
    resize: "vertical",
    boxSizing: "border-box",
    outline: "none",
  },

  feedbackBox: {
    marginTop: "20px",
    padding: "20px",
    background: "#f0fdf4",
    borderRadius: "12px",
    borderLeft: "5px solid #16a34a",
  },

  score: {
    marginTop: "15px",
    fontSize: "18px",
    color: "#2563eb",
  },

  submitArea: {
    textAlign: "center",
    padding: "20px",
  },

  submitButton: {
    padding: "16px 45px",
    background: "#16a34a",
    color: "#fff",
    border: "none",
    borderRadius: "12px",
    fontSize: "17px",
    fontWeight: "700",
    cursor: "pointer",
  },

  resultCard: {
    maxWidth: "600px",
    margin: "30px auto",
    background: "#fff",
    padding: "40px",
    borderRadius: "20px",
    textAlign: "center",
    boxShadow:
      "0 10px 35px rgba(0,0,0,0.08)",
  },

  resultIcon: {
    fontSize: "55px",
  },

  totalScore: {
    fontSize: "60px",
    fontWeight: "800",
    color: "#2563eb",
    margin: "15px 0",
  },

  newInterviewButton: {
    padding: "13px 25px",
    border: "none",
    background: "#2563eb",
    color: "#fff",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: "600",
  },
};